[package]
name = "node-editor-example"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
slint = { path = "../../api/rs/slint" }

[build-dependencies]
slint-build = { path = "../../api/rs/build" }
